### ISSUE TITLE
The Wiki Home Page

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/Pixies-Quest#48]
We need someone, someone who's eyes are even browner than mine, to sprinkle (or spread) some nice BS onto the wiki home page.

https://github.com/KVonGit/Pixies-Quest/wiki/Home/_edit

**Comment by KVonGit** [comment]
Ha!

I can assign people stuff?!?!?

**Comment by XanMag** [comment]
Hmmm... Never had any experience with wiki pages.  Perchance I possibly could perpetuate <strike>BS</strike> persuasive propaganda pertaining to Pixie's Quest.

I wish I could assign stuff to you...

**Comment by KVonGit** [comment]
![image](https://user-images.githubusercontent.com/30656341/31366611-92aca2e6-ad37-11e7-88dd-9d9bbaf2f70a.png)

**Comment by KVonGit** [comment]
>Never had any experience with wiki pages. 

It's just a forum post.  You can use Markdown and everything. (Just like one of these comments.)

We just need a Home Page, which I would think should be the game description.

What the hell IS the game description?

---
Can you not assign me stuff?  You should have access to anything, I think.  (Are you on an actual computer?  Because the mobile site sucks for doing anything besides reading these issues.)

I just wanted to assign someone with something...

---
I wonder if we can assign something to Pixie...

**Comment by XanMag** [comment]
I'll try to assign some things from my pc here in a minute.  💩

**Comment by KVonGit** [comment]
Are you changing the picture?

You got a thumbs-up from DL and I when you posted it.

You are the deciding vote.

---
I don't really care about the wiki, I was just seeing if I could really assign something to someone.

**Comment by KVonGit** [comment]
I'm taking this issue behind the scenes.

**Comment by XanMag** [comment]
If you're all good, so am I.  Use it.

**Comment by KVonGit** [comment]
https://github.com/KVonGit/Pixies-Quest/releases/tag/v0.1.21beta

http://textadventures.co.uk/games/view/jymfhimg00c5cvrdqna7xa/pixies-quest-beta


---
The cover image has been changed.

---
XM

We need a band manager that can get shit done.

I nominate you.

Book us a gig.

**Comment by KVonGit** [comment]
Uh oh...

![image](https://user-images.githubusercontent.com/30656341/31374292-fa874f8a-ad62-11e7-95c9-9cc632e5cd58.png)

**Comment by XanMag** [comment]
What are we uh-oh'ing?
