### ISSUE TITLE
deciphering the text

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/Pixies-Quest#49]
We can:

1. Change the 5s to 13s.
2. Change the scrambled code (scramble it using 5) so it can be deciphered correctly using 5.  (This is my vote, and I'll do the dirt, if you haven't already edited anything, XM.)

NOTE:

I just noticed that it doesn't count if you copy any extra whitespace (before or after the text to unscramble).

I don't think we could do anything about that...

...unless I use a RegEx match, but this is already touchy...

We could also add an object to SCAN or UNSCRAMBLE the text...

I'm still inclined to say f--k it.  Let 'em copy & paste.  It's supposed to be a puzzle, right?

We could always wait and see what Pertex says about having to copy and paste in his next message, too.

**Comment by KVonGit** [comment]
>We could always wait and see what Pertex says about having to copy and paste in his next message, too.

After we change the scramble to 5, of course.  As it stands, the hint doesn't match at all.  (Again, this one is all my fault.  I even clearly remember us discussing using 5.)

**Comment by XanMag** [comment]
Go with whatever is easiest for you, if you're changing it.  I won't complain either way.

**Comment by KVonGit** [comment]
5

**Comment by KVonGit** [comment]
Fixed.

**Comment by KVonGit** [comment]
I think I could make Doctor Agon's text scrambler work now...

...but it would probably be wise to leave that part of this game alone and use Doctor Agon's in the group project or something...

I just don't want to let him down.  I made a big stink about using it in our next game on the first thread XM created regarding the scrambled text.

(I'm still thinking up a good place to add another scene with the rabbit, too.)

**Comment by DarkLizerd** [comment]
Had a thought on the rabbit...
X rabbit
Before you could get too close, you see motion to your left and watch as (name of the location creature) swoops down to snatch the rabbit that is quietly munching on some grass. Suddenly, the rabbit springs up, does a back flip, and kicks down on the top of the creature's head causing it to crash into the ground and roll to a stop. Glancing back at the rabbit, you watch as it flattens its ears back along its body as it stretches out like a diver and dives into the short grass and disappears. "WTF!!!???" you say out loud as you rush over to where the rabbit should have landed, only to see the last of a small black hole shrink down to a dot, then with a "floop" disappears... "WTF!!!" you say again... A sound to your right distracts you and you  watch as the creature, shakes itself then takes off again.
And the glade is quiet again.

**Comment by KVonGit** [comment]
DL, you are one writing son-of-a-buck!

I'm going to put it in the room with me, though.

It will be basically the same, except I'll just notice the rabbit when you examine it, and I'll run at it, triggering the same event (minus the short grass).

Then my NPC will do a bad impersonation of Yosemite Sam: 

KV jumps up and down in place, grumbling, "ooh, I hates that fucking rabbit!

He looks over at you apologetically.  "Sorry about that, Pix.  Rabbits piss me off.  And I hates meeses to pieces, too!"

---
Something like that, only better.

**Comment by DarkLizerd** [comment]
I need to watch more Loony Toons... I've always wanted just like Yosemite Sam!!!

**Comment by KVonGit** [comment]
"Frickin' frackin' mumble-grumble RABBIT!!!"

**Comment by KVonGit** [comment]
My first truck (a '66 Chevy) had the Yosemite Sam mudflaps on it.

![mudflap image](https://i.ebayimg.com/00/s/NjI2WDg0Mg==/z/~dIAAOSwa~BYUIXs/$_58.JPG)

**Comment by DarkLizerd** [comment]
Something like that...

**Comment by KVonGit** [comment]
That may very well be a picture of mudflaps for a big rig, but everything else is just like my old mudflaps...

I miss that big, old truck...

(KV sighs.)

...but I don't miss 8 miles per gallon!

**Comment by KVonGit** [comment]
<samp>

\>x rabbit

Before you can get a good look, RH turns to see what you're looking at, seems to lose every bit of his temper, begins screaming random profanities, and makes a beeline directly towards towards the rabbit.

The rabbit springs up, does a back flip, and kicks RH right in the balls, causing him to fall to the ground, hands on his stomach. 

Glancing back at the rabbit, you watch as it flattens its ears back along its body, stretches out like a diver, and disappears into a hole. 

"What the fuck?" you ask aloud as you rush over to the hole, only to see the last of it shrink down to a dot, then disappear with a soft <i>"floop"</i>.

"What the FUCK!?!" you say again... A sound to your right distracts you and you watch as RH stands up, mumbling profanities.

The only thing you understand is at the end of his Yosemite Sam-like rant, when he looks you right in the eyes and says, "ooh, I hates that fucking rabbit!

He then seems to notice that he's completely lost his shit in front of company, and says, "orry about that, Pix. Rabbits piss me off.
"...and I hates meeses to pieces, too!"
</samp>

**Comment by DarkLizerd** [comment]
> The rabbit springs up, does a back flip, and kicks RH right in the balls, causing him to fall to the ground, hands on his stomach.

Wouldn't that be "below" his stomach???
But I love it!!!
and...
 "orry about that,...
 "Orry about that,... (?)

**Comment by KVonGit** [comment]
I fixed the "sorry" just after I pressed ```Comment```. 😅

**Comment by KVonGit** [comment]
>Wouldn't that be "below" his stomach???

When I receive a swift kick in the balls, I feel it in my stomach more than anything.  After that pain subsides, my attention is drawn back to the pain in my balls.

A light kick to the nuts, though:  that just hurts the nuts.

---
This episode of **Testicle Talk** was made possible by:

# SHARDS OF &infin;
