### ISSUE TITLE
Issue changing rooms after loading a saved game

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/Pixies-Quest#50]
**From Pertex:**

<samp>
<h3> problem with savegame?</h3>

Hi,
there is something strange with that game. I am in Xans world and it displays the wrong room description or shows the wrong descriptions. You can leave this world, it always shows the same description. Only thing is to clear the screen. Then the game seems to be "repaired" again.

If you give me your email I can send you a savegame where you can see the problem.  **NOTE FROM KV:  I gave him my email.**

I don't know if this depends with that problem, but sometimes when I run a walkthrough directly or after a restart, the game seems to break with a white screen.

</samp>

---
This is me (KV) talking again.

I encountered the same errors during the opening sequence, but I couldn't recreate it after the title splash.

I guess I didn't venture far enough into the game, though.

I have run into the white screen during a walkthrough 3 or 4 times, as well, but that happens on other games too, so I thought all the blame belonged to Quest.

**Comment by KVonGit** [comment]
PS

This is only after saving a game and reloading, and it's about to get it's ASS kicked!!!

**Comment by KVonGit** [comment]
I'm pretty sure this is due something I've done.

It happened in DL's opening.

It happens in XM's room.

It doesn't happen in every room, though.  I initially thought it was due to the non-directional exit in DL's room, but I removed that and added an eastern exit:  same error and ONLY in that room, although I started from the first room after the save.  (Exiting to MORE was where the error occurred that time.)

This is XM's room AFTER I left the room.  Look at the panes.  I am in the Word Document room.


![image](https://user-images.githubusercontent.com/30656341/31564836-2d7a905e-b02a-11e7-9aef-a61bbff4adf2.png)

---
I can even interact with the swirling light in the pane, which gives me this:

![image](https://user-images.githubusercontent.com/30656341/31564969-b6a2c3a6-b02a-11e7-8952-f24f97027b84.png)

---
And don't ask about this error:

```
> nw
Error running script: Error compiling expression 'headphoneXM.wornXM': RootExpressionElement: Cannot convert type 'Object' to expression result of 'Boolean'
```

That's the error it throws when an object doesn't exist (or its attribute doesn't exist).

![image](https://user-images.githubusercontent.com/30656341/31565093-21c34638-b02b-11e7-9108-b3eab08b2ba7.png)

---
Oh... That error is fixable.  We just need to create wornXM in the editor and set it to false.

I don't think this will fix the REAL problem, but, if no one objects within 3 minutes I'm going to add the attribute, because I'm in the midst of a battle right now.

**Comment by KVonGit** [comment]
The ```headphoneXM``` error is not real.

I realized this before doing anything, but I still changed it, just to see what happened.  The same thing happened.  I changed it right back.

---
Nothing in DL's room matches anything in XM's room.

Therefore, the chances of it being something I've added into some script somewhere are very high.

---
More on this as it comes in...

**Comment by KVonGit** [comment]
\>> nw
Error running script: Error compiling expression 'headphoneXM.wornXM': RootExpressionElement: Cannot convert type 'Object' to expression result of 'Boolean'

---
I lied.  That happens during normal play.  I'm using REDO to refix it.

**Comment by KVonGit** [comment]
I have no clue why, but I removed ```wornXM``` altogether and replaced all the IF... statements with ```if headphoneXM.worn```, and BOTH errors disappeared.

Hrmm...

---
NOTE:

I added something to XM's script at one point to remove the headphones (or something like that).

When the room-changing error occurred in DL's room, that is ALSO probably due to some turn script I'm running, which checks an attribute that doesn't exist until game.pov is the actual player.

---
More on this as it comes in...

**Comment by XanMag** [comment]
Hahahhaha.  I don't have a fucking clue!!  Looks like you have some essplainin' to do, Ricky.  

I don't know about any of that.  Good luck, hombre.

PS ... been drinking.  Forgive.

**Comment by KVonGit** [comment]
Videos (less than 20 seconds each):

[wtf1.mp4](https://drive.google.com/open?id=0BzGPNwPjOx3TZm82MEV3S3NrZkU)

[wtf2.mp4](https://drive.google.com/open?id=0BzGPNwPjOx3TUEZwRWptQTB4Qk0)

**Comment by KVonGit** [comment]
Now...

If I save AS SOON AS I HAVE ENTERED the hub, there is no problem at all.

BUT...

If I take a turn THEN save:

[wtf3.mp4](https://drive.google.com/open?id=0BzGPNwPjOx3TVzRtaEZ0UWlSRlk)

**Comment by KVonGit** [comment]
We may have to bring in Pixie.

...and he may not be able to figure out what I've done here...

---
Sometimes it does it after three turns, sometimes after each turn.

Clearing the screen fixes it.

When it happens, I'm watching the HTML tools window, and it doesn't create a new output section.

Hrmm...

---
I changed every instance of ```player.parent``` to ```game.pov.parent```, and I disable all of my turn scripts, and...


Wait!

I haven't check the state of the user interface initialisation script!

**Comment by KVonGit** [comment]
It's got me completely baffled.

It seems to do it on the third turn after loading a saved game, but only in certain rooms.  I can find nothing the rooms have in common.  I can find no difference between the rooms that 'house' the error and the ones that don't.

It doesn't do it in my first room, but it DOES in my meadow.

My meadow has no exit.  Of course, the hub has no exit, and it DOESN'T happen there UNLESS you take a turn in the hub before saving.  This seems to be the only room THAT 'works' in, too.  You can save as soon as you enter the other rooms that do this, and it still happens.

**Comment by KVonGit** [comment]
I just made a new game, just to test it.

I just made four rooms, which all connected.

I couldn't recreate the error.

CURSES!!!

**Comment by KVonGit** [comment]
Wait just a minute...

![image](https://user-images.githubusercontent.com/30656341/31570363-9e37b556-b048-11e7-8d23-9e1066ee6631.png)

---
You see how those output sections are numbered?

I believe there was a bug reported where the div output number was ```NaN``` when a saved game was loaded.

I also believe I suggested resetting the div output number to 0.

...but that was only concerning the online player...

Time out.

**Comment by KVonGit** [comment]
Okay...

When we save in the desktop player, it runs this JS function from desktopplayer.js:

```js
function doSave() {
    UIEvent("Save", $("#divOutput").html());
}
```

**Comment by KVonGit** [comment]
This creates the new div (from playercore.js):

```js
function createNewDiv(alignment) {
    var classes = _outputSections.join(" ");
    setDivCount(getDivCount() + 1);
    $("<div/>", {
        id: "divOutputAlign" + getDivCount(),
        style: "text-align: " + alignment,
        "class": classes
    }).appendTo("#divOutput");
    setCurrentDiv("#divOutputAlign" + getDivCount());
}

```

**Comment by KVonGit** [comment]
...here's everything else that goes with ```createNewDiv```:

```js
var _currentDiv = null;

function getCurrentDiv() {
    if (_currentDiv) return _currentDiv;

    var divId = $("#outputData").attr("data-currentdiv");
    if (divId) {
        _currentDiv = $(divId);
        return _currentDiv;
    }

    return null;
}

function setCurrentDiv(div) {
    _currentDiv = $(div);
    $("#outputData").attr("data-currentdiv", div);
}

var _divCount = -1;

function getDivCount() {
    if (_divCount == -1) {
        _divCount = parseInt($("#outputData").attr("data-divcount"));
    }
    return _divCount;
}

function setDivCount(count) {
    _divCount = count;
    $("#outputData").attr("data-divcount", _divCount);
}
```

**Comment by KVonGit** [comment]
Hrmm...

I commented out the line that sets the ```currentDiv``` variable, and it seems to have fixed it.

```js
//var _currentDiv = null;

function getCurrentDiv() {
    if (_currentDiv) return _currentDiv;

    var divId = $("#outputData").attr("data-currentdiv");
    if (divId) {
        _currentDiv = $(divId);
        return _currentDiv;
    }

    return null;
}
```

---
..., but will this mess up a new game???

Find out after this commercial break!

**Comment by KVonGit** [comment]
https://youtu.be/2AdViveJYD0

**Comment by KVonGit** [comment]
Okay...

That seems to have fixed it, and both new games and saved games work.

Now, how the hell do I override that???

It's not even inside of a function...

Hrmm...

**Comment by XanMag** [comment]
I hate to admit the obvious, but... you're on your own on this one.

**Comment by KVonGit** [comment]
I think I may have figured it out, but no promises.

**Comment by KVonGit** [comment]
Did everyone enjoy the commercial break?

Best damned commercial EVER!

**Comment by KVonGit** [comment]
I see what is happening now.

![image](https://user-images.githubusercontent.com/30656341/31571318-e576cff8-b055-11e7-8b1e-c877bbd05281.png)

divOutputAlign7 was the last thing Quest printed to STDOUT before the save.

After the save, this line sets divOutputAlign to 0.

Don't ask me what happens to 1, but Quest picks back up with divOutputAlign2 once you take the first turn after loading the saved game.

Now...

When you get it back up to divOutputAlign7, Quest gets confused and prints out the divOutputAlign7 that is already saved.  Presumably because it searches for the output to print, starting from the beginning of the document?

---
This may ALL be BS!

**Comment by KVonGit** [comment]
This is what Quest is working from (from the saved game file):

```xml
  <output>
    <html><![CDATA[<div id="divOutputAlign5" style="text-align: left" class="section1"><style> #txtCommand {outline:none;box-shadow:0px 0px 5px 5px #296231;} #location, #status, .ui-widget-header { background-color:#296231;border:1px solid #296231;background-image:none;}</style>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <style>#gameBorder {background:white;}body{background:white} </style><span style="font-family:'Source Sans Pro', Georgia, serif;color:Black;font-size:12pt;"><b>Cave</b></span><br><span style="font-family:'Source Sans Pro', Georgia, serif;color:Black;font-size:12pt;">You have made your way through most of the Wumpus cavern and are nearing in on the most foul creature itself. You recheck your sword: sharp as it ever has been. Your shield, at the ready. Your armor does not have a single gap that would let the creature harm you. <br><br>You are startled when a fox jumps up onto a rock in front of you. Quickly, you draw your sword to defend yourself. You chuckle at being startled by an animal. Just as you relax a bit, the fox stands on its hind legs, places a Robin Hood-like hat on his head, draws a two-foot rapier, swishes it around, then takes a fencing pose facing you.<br></span><br><span style="font-family:'Source Sans Pro', Georgia, serif;color:Black;font-size:12pt;">You can see a <a id="verblink1" style="font-family:'Source Sans Pro', Georgia, serif;color:Blue;font-size:12pt;" class="cmdlink elementmenu" data-elementid="red fox1" data-verbs="Look at/Take/Who/Treasure/Fight/Attack">red fox</a>.<br></span><br><span style="font-family:'Source Sans Pro', Georgia, serif;color:Black;font-size:12pt;">There is an exit to the <a style="font-family:'Source Sans Pro', Georgia, serif;color:Blue;font-size:12pt;" class="cmdlink exitlink" data-elementid="exit1" data-command="go east">east</a>.</span><br></div><div id="divOutputAlign6" style="text-align: left" class=""></div><div id="divOutputAlign7" style="text-align: left" class="section3"><span style="font-family:'Source Sans Pro', Georgia, serif;color:Black;font-size:12pt;"></span><br><span style="font-family:'Source Sans Pro', Georgia, serif;color:Black;font-size:12pt;">&gt; save</span><br></div>]]></html>
  </output>
```

**Comment by KVonGit** [comment]
This is the last output element in the saved game file:

```html
<div id="divOutputAlign7" style="text-align: left" class="section3"><span style="font-family:'Source Sans Pro', Georgia, serif;color:Black;font-size:12pt;"></span>
<br><span style="font-family:'Source Sans Pro', Georgia, serif;color:Black;font-size:12pt;">&gt; save</span>
<br></div>
```

**Comment by KVonGit** [comment]
Mumble, grumble...
![image](https://user-images.githubusercontent.com/30656341/31571736-12bd74be-b05e-11e7-9beb-66d464bcdf01.png)


---

# MAN-ROAR!!!

**Comment by KVonGit** [comment]
Quest has to walk around with its hand in my back pocket for a while.  It's my bitch right now.

http://textadventures.co.uk/forum/quest/topic/ik0dbblaq0o5fdqq7nuwia/js-function-to-find-the-last-divoutputalign-in-a-saved-game#039786de-db1b-4325-b3c4-6aadd7e9722f

---
FIXED!!!

---
XanMag, SonicDayAir me a beer!!!

**Comment by KVonGit** [comment]
[victory music](https://youtu.be/DhlPAj38rHc)
