### ISSUE TITLE
Game Check-in/Check-out

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/Pixies-Quest#51]
# If someone has the game checked out, and you want to add something on, just post a comment here to alert whoever that particular individual is.

## If I have it checked out, I'll upload what I've currently got and pass it on over.

- [ ] DL

- [ ] KV

- [ ] XM

- [x] no one

Current version: 0.1.40-beta
Quick notes:

**Comment by KVonGit** [comment]
Checking it out.

---
The changing rooms after loading a saved game problem has already thoroughly pissed me off once.

I got it around it in the opening by creating a SAVE command that prints "You can't save the game during the opening sequence."

That was after I tried everything I could think of for at least three hours.

It wants to fuck with me again now?!?

Fuck yeah, I can dig THAT shit!  Let's do it!

It's on like **Donkey Kong**, motherfuckers!!!

![DK](https://pre00.deviantart.net/edde/th/pre/i/2015/121/4/2/punch_out_donkey_kong_by_nanobuds-d8rt5z7.png)

**Comment by KVonGit** [comment]
Checked.

Back.

In.

0.1.40

---
I'm pretty sure I messed AT LEAST one thing up that previously worked perfectly fine.

I just now realized that I didn't run the walkthrough...

Oh well.

If I did, I'll revert to the last version and add the two little, bitty, teensy-weensy scripts that fixed it.

---
I ***think***  all we lack now is the stuff XM listed during his play-through.

---
The two things everyone will complain about:

- Crate Mart
- Unscrambling the text

Well, guess what, everyone?

We did that on purpose!

There are TWO puzzles in the whole game!  TWO!!!

And you can enter HINT at every turn in Crate Mart.  The hint system will walk you right through it!

You're on your own with the scrambled text, though.

Perhaps you aren't in the correct state of mind if you can't read that text...

**Comment by KVonGit** [comment]
UPDATE:

I just ran the walkthrough...

**Comment by KVonGit** [comment]
Aargh!

This Issue was open!?!?

Closed, but still active.

**Comment by KVonGit** [comment]
Checking it out (just like a hot redhead).

**Comment by KVonGit** [comment]
Thinking about adding an Ask to HK.

ASK HK ABOUT STORIES/MOVIES/BOOKS/MUSIC/GAMES

http://textadventures.co.uk/forum/general/topic/wxc3xmfxm0geci-hj1wrma/what-is-your-favorite-story-edit-or-what-are-some-of-the-stories-you-really#5ae50bca-9b67-44ab-8f82-0100e51da8cc


If I put that entire post (just the one post, mind you, not the thread) in the game, do you think Quest would blow up?

**Comment by XanMag** [comment]
Yes.  Yes I do.

**Comment by KVonGit** [comment]
It didn't blow it up.  (I tested it on my old computer, just in case it did!)

---
Checked in: 0.1.41-beta.

- Fixed the damned divOutputAlign by altering clearScreen, thanks to mrangel
- Added ASK HK ABOUT HIS FAVORITE STORY
- Added an init script after the first load if the game finds the web player
    - This runs ShowRoomDescription when a saved game is loaded, to 'fix' the cleared screen on load
- Probably did some other stuff, too...

**Comment by XanMag** [comment]
Checking out...

**Comment by XanMag** [comment]
Checked it in as: Pixie's Quest 0.1.42

The other .aslx files are still there.  I didn't want to fuck stuff up by deleting things I shouldn't.  I'll leave that to someone more competent.

Also, I ddn't change much at all, just those little buggers found by Pertex and those I made note of in the things to change thread I mentioned.

**Comment by KVonGit** [comment]
>Checked it in as: Pixie's Quest 0.1.42

🎸 🎵 

---
>The other .aslx files are still there.   I didn't want to fuck stuff up by deleting things I shouldn't. 

I used to go out of my way to do the same thing.

You can't mess things up on GitHub.  Everything can be reverted.

I can take it back to day 1 (or anywhere in-between) with one click:

![image](https://user-images.githubusercontent.com/30656341/31583203-108c9b76-b15c-11e7-87aa-e56a04722ee7.png)

---
You did no wrong, nor did you cause me any extra work.  I just thought I'd save you from the extra steps next time.

This repo is impervious to our bumbling!  (Otherwise, I'd have broken it a long time ago!)

---
>I'll leave that to someone more competent.

♿️ "Are you referring to _moi_? "

**Comment by KVonGit** [comment]
You guys wanna see why GitHub Desktop is awesome?

I open up XM's latest commit in full code view, CTRL+A, then CTRL +C.

I open the main game in full code view.  CTRL+A, Delete, CTRL+V.

Now I've pasted Xan's game into the actual game.

I press Play from Code View.  This allows me to test it out AND saves the file to my hard drive, but I'll still be able to use UNDO in code view to get the game back to it's original state JUST IN CASE.  If I returned to GUI mode, the ability to undo would be GONE FOREVER.   

NOTE:  This game is on GitHub, so that wouldn't matter in this case, but that's nice to know when you CAN seriously lose the last working version of your game.  ANYWAY, back to GitHub Desktop.

---
RECAP: I did all the copying and pasting and pressed Play.

Now let's check out what happens when we open GitHub Desktop and scroll down:

![image](https://user-images.githubusercontent.com/30656341/31583296-675e83cc-b15e-11e7-81f3-0a79eeda6177.png)

---
If you keep on scrolling down, you will see all of the changes in this same view.

Awesome, right?

NOTE TO SELF:  That was decreasing HEALTH not the SCORE!  **DOH!!!**

---
Now, I'm going in the directory on my hard drive and deleting that game XM just submitted:

![image](https://user-images.githubusercontent.com/30656341/31583312-ca35f08e-b15e-11e7-9e02-53a7e62421d3.png)

![image](https://user-images.githubusercontent.com/30656341/31583320-ed83f95a-b15e-11e7-8cc0-072a2b47ac05.png)

---
...and back to GitHub Desktop...

![image](https://user-images.githubusercontent.com/30656341/31583327-33ddd43e-b15f-11e7-8a5c-6c22511c0cf2.png)

Look!  A new file has appeared in the tree on the left!  WTF is that?!?  Let's click it!!!

![image](https://user-images.githubusercontent.com/30656341/31583333-580bdbbc-b15f-11e7-8723-3fd2b8599bbf.png)

---
Whoa!  

So GitHub Desktop is showing us the differences between this repository in my local directory (meaning the one on MY hard drive) VS the actual repository as it is on GitHub.

In this example, it displays all the changes in the main file AND alerts us that one file has been completely deleted.

---
Now, this was the point where I had absolutely no clue how to proceed the first time I used GitHub Desktop.

You must put something in the summary field (you can leave description blank if you like), then 'Commit to master' will become clickable.

![image](https://user-images.githubusercontent.com/30656341/31583386-632fc34a-b160-11e7-9e7f-27b848c754fc.png)

---
Wait a second, though...

Did I change the version number in the actual game file?

I click on that file in the tree again, scan the changes, and no.  I don't see that change.  So, I go back to the game (which is still running in Quest right now, remember?  Good!  I knew you could).  I stop the game, which puts me back in Code View.  I shall now change the release number to 0.1.42-beta, click Save in Quest, then we'll look at GitHub Desktop again:

NOTE:  I went ahead and properly filled in the commit's Summary and put a Description too.

![image](https://user-images.githubusercontent.com/30656341/31583444-9dcd4c9c-b161-11e7-8bd3-aedf5a181c21.png)

---
Now, I shall commit to master.  This is the screen immediately after clicking:

![image](https://user-images.githubusercontent.com/30656341/31583454-f1a89dc6-b161-11e7-8bad-bee32278f36a.png)

---
Uh...

What happened?  Am I done?  Sigh...  I guess I'll go check things out online to confirm it:

![image](https://user-images.githubusercontent.com/30656341/31583480-7da0849c-b162-11e7-85ce-6c73f508011e.png)

Nope.  My changes aren't there.  I must need to press that **Push origin** button...

![image](https://user-images.githubusercontent.com/30656341/31583502-eb8feab0-b162-11e7-8483-1b86ea75fd62.png)

---
Now, I've pressed **Push origin**.

This screen means your local files are synced with the files in the main repo:

![image](https://user-images.githubusercontent.com/30656341/31583515-140666ea-b163-11e7-9c47-c47257e66683.png)

---
### **Done.**

---
---
---
# ALTERNATE METHOD
# MY EDITING & COMMIT PUSHING METHOD (WHICH BYPASSES A COUPLE OR FEW OF THE ABOVE STEPS)

When editing the game, I edit the game file that is in my local GitHub directory.

When I save a change, I simply open GitHub Desktop, type in "update to blah-blah-blah", click commit, and click **Push origin**.

That's it.  

No more steps my way.

---
ANOTHER NOTE:  You can do all of this from the terminal (Command or Powershell or Bash) with commands like ```git fetch```, ```git status```, ```git commit -m "Update to blah-blah-blah```,  ```git push```, ```git pull```, and (to see the changes you've made before committing) either ```diff file1 file2 > todaysDIFF.txt && cat todaysDIFF.txt``` or you could use other DIFF viewing tools (like Merge).

---
This has been brought to you by:

🍺 &  🍕  & 🍻 

### BEER AND PIZZA AND MORE BEER:
#### The cornerstone of any enjoyable Saturday.

**Comment by KVonGit** [comment]
PS

Now, if I want to, I can click on **History** (just above the file tree), select the last commit, right-click, and restore XanMag's game.  (I could do the same with any commit ever made by anyone on this repo. 
 That, my fine, feathered friends, is the beauty of GitHub.)

![image](https://user-images.githubusercontent.com/30656341/31583758-86a52f30-b166-11e7-9f21-2abed6a416ef.png)

---
### SIDENOTE:

# DL!!!
## I just noticed that you snuck in something awesome-looking!

**Comment by KVonGit** [comment]
Alright, stop what you're doin',
'cause we're about to ruin
all the text adventures that you're used to.

This game's funny,
and there's even a puzzle or three.
So, yo, Pix!  We hope you're ready to see!

Now, gather round.
We're the new crew in town,
and our sound's laid down by @XanMag .

We'll snatch up all the Shards of &infin; you've got on yourself!
So, just let us introduce ourselves...

https://youtu.be/y38Ec57yMG8

**Comment by XanMag** [comment]
Ha.  Priceless.  You were really lacking some sleep, huh?  This post is great.

**Comment by KVonGit** [comment]
I suppose that we pose our prose too close to each other's prose,
and the effect just might leave ya' wrecked,
but our shit's BEST when we juxtapose.

**Comment by KVonGit** [comment]
Checking it out.

**Comment by KVonGit** [comment]
Oh, no I'm not!

I didn't scroll up.  XM's got it checked out.

**Comment by KVonGit** [comment]
Oh.  That was 11 hours ago.  😅

Checking it out.

**Comment by XanMag** [comment]
I noted I checked it in.  Like 1,258 times.  Didn't I?

**Comment by KVonGit** [comment]
>I noted I checked it in.  Like 1,258 times.  Didn't I?

Yep.

I just scrolled up there to check it out and saw XM checked and thought you were back at it.

Then, I almost thought for a second, but then I remembered a few times when I forgot to uncheck that damned box myself, and decided to see what time you edited that post last.

---
Public Service Announcement

If you can comprehend what I'm saying, you are just as crazy as me!

**Comment by KVonGit** [comment]
Hey, XanMag....

I'm watching Poltergeist right now, right?  (The one with Coach, not that new piece of shit.  The OLD piece of shit!  With that redhead I love.  What's her name?  Damn and blast!  The mom from Dutch (where Al Bundy goes to get the brat from boarding school for Thanksgiving)... JoBeth Williams!!!)

Anyway...

When you can see the light, what are the instructions, XM?

1. Look into the light.
2. DON'T look into the light!!!
3. Look into the light.

(Isn't that how it went?)

---
All of that is insignificant, of course.  The point is: do we want a LOOK INTO THE LIGHT verb that just gives a funny response?

(If yes, I will ask you for said response.)

---
This message was brought to you by:

[WANG](https://youtu.be/BvcdhrZl_l4)

Some people enjoy playing golf, but I'd rather stay at home and play with my WANG.

**Comment by KVonGit** [comment]
It only prints this on save when playing online:

![image](https://user-images.githubusercontent.com/30656341/31586413-1c1f3f90-b196-11e7-8f22-20696581ce40.png)

**Comment by XanMag** [comment]
I thought it was "Don't go toward the light"?  Wasn't it?

Anyway... I'm not feeling super creative right now unfortunately.  I will trust a response to you if you want to write one.  

I'll be back later, fucker.

**Comment by KVonGit** [comment]
I just found this.  (Still haven't got the email notification.  They have up to a 12 hour delay sometimes.)

>I thought it was "Don't go toward the light"?  Wasn't it?

Maybe... I'm always thinking how I'd marry JoBeth Williams.

>I'm not feeling super creative right now unfortunately. 

I have also come down with the block.

>I will trust a response to you if you want to write one.

Nah.  I honestly forgot all about this, and I just committed all the v1.0.0 files everywhere.

If it just tickled your fancy, we can add it though.

If you don't care, I don't care, and I vote we push the DONE button.

If you wonder whether or not I'm ready for you to submit the "THANK YOU" release post or do whatever:  I am ready.  If I don't respond, I'm asleep.

>I'll be back later

Thanks for the warning!!!

**Comment by KVonGit** [comment]
Stats just before releasing:

![image](https://user-images.githubusercontent.com/30656341/31693698-b72fd1b8-b365-11e7-88d2-2fe3767ec4bc.png)

**Comment by XanMag** [comment]
That "how to score" score tab...
Is that in reference to this game or to women? 

    On Tuesday, October 17, 2017 7:06 PM, K.V. <notifications@github.com> wrote:
 

 Stats just before releasing:—

**Comment by KVonGit** [comment]
>That "how to score" score tab...
Is that in reference to this game or to women?

Initially, the only text on the page was:

# You're NEVER gonna score!
### Uh... Huh-huh-huh!  Huh-huh-huh-huh-huh!
