### ISSUE TITLE
Family-friendly version

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/Pixies-Quest#52]
I am <s>editing currently</s> currently editing.

I believe a family-friendly version would be nice.

I have already fixed all the expletives.

I was considering changing the beer to root-beer, but I think beer is okay.  (Don't you?)

SO...

The only thing left is the Cheech & Chong task.

I once saw NEXT MOVIE on a local channel.

Cheech & Chong were toting around a big bag of DIAMONDS, and Cheech's red-headed cousin (Red) was in the diamond 'business'.

This isn't exactly what I want to do in the game, but you get the general gist, @XanMag .

Should I remove the task?  Or make it some other object (like a snack or some candy) or something?

**Comment by DarkLizerd** [comment]
It would be easiest to delete/skip over the "too adult" stuff...
But if you are just changing beer to root beer, bag to diamonds to bag of candy...
Then it sounds like you are catering to a younger crowd, one that may not be able to complete all the "Pixie tasks" anyway...
Altho, there are those adults that don't like the "adult language" in movies and games.

**Comment by KVonGit** [comment]
DL,

All I think I found in your stuff was one occurrence of ASS which I changed to BEHIND.

You know, that may have been in MY part, now that I think about it!

That was RH chasing the rabbit.  That's why I connected it to you for a moment.

---
I was thinking maybe a fish-taco tree in XanMag's Daydream room.

You must hand it to Gal first, so she can heat it up for XM.


---
Of course, I'm not moving on this if both of you guys don't approve.

I think a separate game would be the best route, too.  I don't trust it with the juicy stuff hidden in there enough to label it 'family-friendly'.

---
As far as the difficulty level is concerned, you can enter HINT at any time for a hint to select from a menu of clues concerning anything (or anything that isn't XanMag's) in the room.

During my two hard parts, when you enter HINT, you get one specific message, which you can pretty much copy and paste as a command.

I also listed everything about all of my stuff on the wiki.

I beat Zork 1 and a couple of other INFOCOM games when I was between the age of 8 and 10.

Hitchhiker's and the rest were a little to <s>advanced</s> far-fetched for me to get through, though... 

...but I still had fun trying!

(NOTE:  I was also allowed to watch Sam Kinison, Richard, Pryor, Eddie Murphy, George Carlin, Rodney Dangerfield, etc.  when I was that age.  So I was admittedly 'different' than the other kids.)

**Comment by KVonGit** [comment]
Maybe Xan wants a Butterscotch Jellybean?


---
<samp>

\>ask Gal for Butterscotch Jellybean
Gal slaps you, then calmly says, "no."

\>ask Gal for Butterscotch Jellybean for XanMag
"Xanny wants another BJ?"  Gal giggles.  "Well, you just lead me to him, Mr. Pix!  I'll give him the  juiciest BJ he's ever had!"

Gal is now following you.

</samp>

**Comment by XanMag** [comment]
>"Xanny wants another BJ?" Gal giggles. "Well, you just lead me to him, Mr. Pix! I'll give him the juiciest BJ he's ever had!"Gal is now following you. 
That is HILARIOUS.
As for the other stuff.  I LOVE fish tacos, so you can certainly exchange that for a child friendly version if you feel the motivation to do so!
Let me know if you need help!

**Comment by KVonGit** [comment]
Okay...

What if XanMag has a sarsaparilla plant in his Daydream room, because he REALLY likes <s>beer</s> root-beer.

TASK:  
- Get a root from the sarsaparilla plant.  
- Give it to Gal in the root-beer bar.  
- Answer what XM's favorite root-beer is.  
- Get the root-beer.  
- Give it to XM.  
- XM gives you a SuperSpellUnscramblerThingyV2.0XM.  It has a button, a knob, a slide, a door, and a crank.  

TASK:
- You have to push the button on the SuperSpellUnscramblerThingyV2.0XM while its door is closed and you are in the WordDocument room to scan the text.  
- Then you: 
1. turn the knob to 5
2. slide the slide
3. turn the crank
4. open the door (in that order)
5. get the IdeaInAnEnvelope.
6. put it on the pedestal

**Comment by XanMag** [comment]
I am okay with that!

**Comment by DarkLizerd** [comment]
For a little added complexity... check out what I did for Wumpus 3.5 for selecting your playing difficulty/ options...
http://textadventures.co.uk/games/view/g4jaujz2ceipk6vi3cfx0a/wumpus-3-0
for the code, look in the room: Cave...
And option would be to set the slide to a certain number, turn the crank so that it lines up to the correct number, turn the knob to it's number, and push the button to decode the message... 
Then open the door to get the decoded message...

**Comment by KVonGit** [comment]
Fuck a family-friendly version.
